apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiln
  labels:
    app.kubernetes.io/name: kiln
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kiln
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kiln
    spec:
      containers:
        - name: kiln
          image: "{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
  strategy:
    type: Recreate