apiVersion: v1
kind: Service
metadata:
  name: kiln
  labels:
    app.kubernetes.io/name: kiln
spec:
  selector:
    app.kubernetes.io/name: kiln
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
